/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslationsRouteImport } from './routes/translations'
import { Route as TheanswerlayerRouteImport } from './routes/theanswerlayer'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataConnectorsIndexRouteImport } from './routes/data-connectors/index'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'

const TranslationsRoute = TranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => rootRouteImport,
} as any)
const TheanswerlayerRoute = TheanswerlayerRouteImport.update({
  id: '/theanswerlayer',
  path: '/theanswerlayer',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataConnectorsIndexRoute = DataConnectorsIndexRouteImport.update({
  id: '/data-connectors/',
  path: '/data-connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/languages': typeof LanguagesRoute
  '/success': typeof SuccessRoute
  '/theanswerlayer': typeof TheanswerlayerRoute
  '/translations': typeof TranslationsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/data-connectors/': typeof DataConnectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/languages': typeof LanguagesRoute
  '/success': typeof SuccessRoute
  '/theanswerlayer': typeof TheanswerlayerRoute
  '/translations': typeof TranslationsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/data-connectors': typeof DataConnectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/languages': typeof LanguagesRoute
  '/success': typeof SuccessRoute
  '/theanswerlayer': typeof TheanswerlayerRoute
  '/translations': typeof TranslationsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/data-connectors/': typeof DataConnectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/languages'
    | '/success'
    | '/theanswerlayer'
    | '/translations'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/data-connectors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/languages'
    | '/success'
    | '/theanswerlayer'
    | '/translations'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/data-connectors'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/languages'
    | '/success'
    | '/theanswerlayer'
    | '/translations'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/data-connectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LanguagesRoute: typeof LanguagesRoute
  SuccessRoute: typeof SuccessRoute
  TheanswerlayerRoute: typeof TheanswerlayerRoute
  TranslationsRoute: typeof TranslationsRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  DataConnectorsIndexRoute: typeof DataConnectorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translations': {
      id: '/translations'
      path: '/translations'
      fullPath: '/translations'
      preLoaderRoute: typeof TranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theanswerlayer': {
      id: '/theanswerlayer'
      path: '/theanswerlayer'
      fullPath: '/theanswerlayer'
      preLoaderRoute: typeof TheanswerlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-connectors/': {
      id: '/data-connectors/'
      path: '/data-connectors'
      fullPath: '/data-connectors/'
      preLoaderRoute: typeof DataConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LanguagesRoute: LanguagesRoute,
  SuccessRoute: SuccessRoute,
  TheanswerlayerRoute: TheanswerlayerRoute,
  TranslationsRoute: TranslationsRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  DataConnectorsIndexRoute: DataConnectorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
