/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslationsRouteImport } from './routes/translations'
import { Route as TheanswerlayerRouteImport } from './routes/theanswerlayer'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as HireYourTeamRouteImport } from './routes/hire-your-team'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DailySignalRouteImport } from './routes/daily-signal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataConnectorsIndexRouteImport } from './routes/data-connectors/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiBlogRssRouteImport } from './routes/api/blog/rss'

const TranslationsRoute = TranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => rootRouteImport,
} as any)
const TheanswerlayerRoute = TheanswerlayerRouteImport.update({
  id: '/theanswerlayer',
  path: '/theanswerlayer',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const HireYourTeamRoute = HireYourTeamRouteImport.update({
  id: '/hire-your-team',
  path: '/hire-your-team',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DailySignalRoute = DailySignalRouteImport.update({
  id: '/daily-signal',
  path: '/daily-signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataConnectorsIndexRoute = DataConnectorsIndexRouteImport.update({
  id: '/data-connectors/',
  path: '/data-connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRssRoute = ApiBlogRssRouteImport.update({
  id: '/api/blog/rss',
  path: '/api/blog/rss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/daily-signal': typeof DailySignalRoute
  '/features': typeof FeaturesRoute
  '/hire-your-team': typeof HireYourTeamRoute
  '/languages': typeof LanguagesRoute
  '/pricing': typeof PricingRoute
  '/success': typeof SuccessRoute
  '/theanswerlayer': typeof TheanswerlayerRoute
  '/translations': typeof TranslationsRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/blog/': typeof BlogIndexRoute
  '/data-connectors/': typeof DataConnectorsIndexRoute
  '/api/blog/rss': typeof ApiBlogRssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/daily-signal': typeof DailySignalRoute
  '/features': typeof FeaturesRoute
  '/hire-your-team': typeof HireYourTeamRoute
  '/languages': typeof LanguagesRoute
  '/pricing': typeof PricingRoute
  '/success': typeof SuccessRoute
  '/theanswerlayer': typeof TheanswerlayerRoute
  '/translations': typeof TranslationsRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/blog': typeof BlogIndexRoute
  '/data-connectors': typeof DataConnectorsIndexRoute
  '/api/blog/rss': typeof ApiBlogRssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/daily-signal': typeof DailySignalRoute
  '/features': typeof FeaturesRoute
  '/hire-your-team': typeof HireYourTeamRoute
  '/languages': typeof LanguagesRoute
  '/pricing': typeof PricingRoute
  '/success': typeof SuccessRoute
  '/theanswerlayer': typeof TheanswerlayerRoute
  '/translations': typeof TranslationsRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/blog/': typeof BlogIndexRoute
  '/data-connectors/': typeof DataConnectorsIndexRoute
  '/api/blog/rss': typeof ApiBlogRssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/daily-signal'
    | '/features'
    | '/hire-your-team'
    | '/languages'
    | '/pricing'
    | '/success'
    | '/theanswerlayer'
    | '/translations'
    | '/api/contact'
    | '/blog/$slug'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/blog/'
    | '/data-connectors/'
    | '/api/blog/rss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/daily-signal'
    | '/features'
    | '/hire-your-team'
    | '/languages'
    | '/pricing'
    | '/success'
    | '/theanswerlayer'
    | '/translations'
    | '/api/contact'
    | '/blog/$slug'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/blog'
    | '/data-connectors'
    | '/api/blog/rss'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/daily-signal'
    | '/features'
    | '/hire-your-team'
    | '/languages'
    | '/pricing'
    | '/success'
    | '/theanswerlayer'
    | '/translations'
    | '/api/contact'
    | '/blog/$slug'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/blog/'
    | '/data-connectors/'
    | '/api/blog/rss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DailySignalRoute: typeof DailySignalRoute
  FeaturesRoute: typeof FeaturesRoute
  HireYourTeamRoute: typeof HireYourTeamRoute
  LanguagesRoute: typeof LanguagesRoute
  PricingRoute: typeof PricingRoute
  SuccessRoute: typeof SuccessRoute
  TheanswerlayerRoute: typeof TheanswerlayerRoute
  TranslationsRoute: typeof TranslationsRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DataConnectorsIndexRoute: typeof DataConnectorsIndexRoute
  ApiBlogRssRoute: typeof ApiBlogRssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translations': {
      id: '/translations'
      path: '/translations'
      fullPath: '/translations'
      preLoaderRoute: typeof TranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theanswerlayer': {
      id: '/theanswerlayer'
      path: '/theanswerlayer'
      fullPath: '/theanswerlayer'
      preLoaderRoute: typeof TheanswerlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-your-team': {
      id: '/hire-your-team'
      path: '/hire-your-team'
      fullPath: '/hire-your-team'
      preLoaderRoute: typeof HireYourTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-signal': {
      id: '/daily-signal'
      path: '/daily-signal'
      fullPath: '/daily-signal'
      preLoaderRoute: typeof DailySignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-connectors/': {
      id: '/data-connectors/'
      path: '/data-connectors'
      fullPath: '/data-connectors/'
      preLoaderRoute: typeof DataConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/rss': {
      id: '/api/blog/rss'
      path: '/api/blog/rss'
      fullPath: '/api/blog/rss'
      preLoaderRoute: typeof ApiBlogRssRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DailySignalRoute: DailySignalRoute,
  FeaturesRoute: FeaturesRoute,
  HireYourTeamRoute: HireYourTeamRoute,
  LanguagesRoute: LanguagesRoute,
  PricingRoute: PricingRoute,
  SuccessRoute: SuccessRoute,
  TheanswerlayerRoute: TheanswerlayerRoute,
  TranslationsRoute: TranslationsRoute,
  ApiContactRoute: ApiContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  BlogIndexRoute: BlogIndexRoute,
  DataConnectorsIndexRoute: DataConnectorsIndexRoute,
  ApiBlogRssRoute: ApiBlogRssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
